services:
    _defaults:
        autowire: true
        autoconfigure: true

    BCS\ContaoSignatureFormField\EventListener\PrepareFormDataListener:
        arguments:
            $projectDir: '%kernel.project_dir%'
